---
version: 2
updates:
  # docker images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    assignees:
      - cedricziel
    reviewers:
      - cedricziel
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    assignees:
      - cedricziel
    reviewers:
      - cedricziel
    groups:
      mui:
        patterns:
          - "@mui/*"
      react:
        patterns:
          - "react"
          - "react-dom"

  # Backend Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    assignees:
      - cedricziel
    reviewers:
      - cedricziel
