[general]
# Directory for template files
dirs = ["templates"]

# Extension for template files
extension = "html"

# Custom syntax for escaping
escaper = "askama::Html"

# Register filters
[[general.filters]]
name = "json_encode"
path = "crate::web::filters::json_encode"
