export default {
  ADD_COMMENT: 'Add Comment',
  CLEAN_UP: 'Clean up Blocks',
  COLLAPSE_ALL: 'Collapse Blocks',
  COLLAPSE_BLOCK: 'Collapse Block',
  DELETE_BLOCK: 'Delete Block',
  DELETE_X_BLOCKS: 'Delete %1 Blocks',
  DISABLE_BLOCK: 'Disable Block',
  DUPLICATE_BLOCK: 'Duplicate',
  ENABLE_BLOCK: 'Enable Block',
  EXPAND_ALL: 'Expand Blocks',
  EXPAND_BLOCK: 'Expand Block',
  EXTERNAL_INPUTS: 'External Inputs',
  HELP: 'Help',
  INLINE_INPUTS: 'Inline Inputs',
  LISTS_CREATE_WITH_CONTAINER_TITLE_ADD: 'Add',
  LISTS_CREATE_WITH_ITEM_TITLE: 'Item',
  REMOVE_COMMENT: 'Remove Comment',
  RENAME_VARIABLE: 'Rename Variable...',
  RENAME_VARIABLE_TITLE: 'Rename all "%1" variables to:',
  UNDO: 'Undo',
  REDO: 'Redo',
  VARIABLES_DEFAULT_NAME: 'item',
  VARIABLE_ALREADY_EXISTS: 'A variable named "%1" already exists.',
  VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE: 'A variable named "%1" already exists for another type: "%2".',
};
